# Generated by Django 2.2.13 on 2021-05-20 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0585_auto_20210420_0845'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('email', 'Email notification'), ('web', 'Web notification')], max_length=10, verbose_name='Type')),
                ('payload', models.TextField(verbose_name='Payload')),
                ('state', models.CharField(choices=[('pending', 'En attente'), ('sent', 'Sent'), ('read', 'Read')], default='pending', max_length=10, verbose_name='État')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Créé')),
                ('sent_datetime', models.DateTimeField(editable=False, null=True, verbose_name='Sent at')),
                ('read_datetime', models.DateTimeField(editable=False, null=True, verbose_name='Read at')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.Person')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
