# Generated by Django 3.2.16 on 2023-01-20 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0647_merge_20230113_1039'),
        ('osis_notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.person'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.CheckConstraint(check=models.Q(('person_id__isnull', True), ('type', 'WEB_TYPE'), _negated=True), name='person_required_for_web'),
        ),
    ]
